import { DataPlan } from './plans.dto';

const airtelSmePlans: Array<DataPlan> = [
  {
    id: 416,
    dataplan_id: '416',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 417,
    dataplan_id: '417',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 419,
    dataplan_id: '419',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 420,
    dataplan_id: '420',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '100.0MB',
  },
  {
    id: 421,
    dataplan_id: '421',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '500.0MB',
  },
  {
    id: 422,
    dataplan_id: '422',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 423,
    dataplan_id: '423',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '300.0MB',
  },
  {
    id: 424,
    dataplan_id: '424',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '15.0GB',
  },
  {
    id: 425,
    dataplan_id: '425',
    network_id: 4,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '20.0GB',
  },
];

const airtelGiftingPlans: Array<DataPlan> = [
  {
    id: 398,
    dataplan_id: '398',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '1.5GB',
  },
  {
    id: 400,
    dataplan_id: '400',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '5.0GB',
  },
  {
    id: 401,
    dataplan_id: '401',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '500.0MB',
  },
  {
    id: 403,
    dataplan_id: '403',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '3.5GB',
  },
  {
    id: 404,
    dataplan_id: '404',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '6.0GB',
  },
  {
    id: 405,
    dataplan_id: '405',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '300.0MB',
  },
  {
    id: 406,
    dataplan_id: '406',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '2.0GB',
  },
  {
    id: 407,
    dataplan_id: '407',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 408,
    dataplan_id: '408',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '4.0GB',
  },
  {
    id: 410,
    dataplan_id: '410',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '10.0GB',
  },
  {
    id: 411,
    dataplan_id: '411',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.0GB',
  },
  {
    id: 412,
    dataplan_id: '412',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '3.0GB',
  },
  {
    id: 413,
    dataplan_id: '413',
    network_id: 4,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '8.0GB',
  },
];

const airtelCorporatePlans: Array<DataPlan> = [
  {
    id: 302,
    dataplan_id: '302',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.0GB',
  },
  {
    id: 303,
    dataplan_id: '303',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 1,
    name: '100.0MB',
  },
  {
    id: 305,
    dataplan_id: '305',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '500.0MB',
  },
  {
    id: 306,
    dataplan_id: '306',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 307,
    dataplan_id: '307',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '4.0GB',
  },
  {
    id: 314,
    dataplan_id: '314',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 315,
    dataplan_id: '315',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '18.0GB',
  },
  {
    id: 316,
    dataplan_id: '316',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '300.0MB',
  },
  {
    id: 317,
    dataplan_id: '317',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '25.0GB',
  },
  {
    id: 440,
    dataplan_id: '440',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '6.0GB',
  },
  {
    id: 441,
    dataplan_id: '441',
    network_id: 4,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
];

const airtelAwoofPlans: Array<DataPlan> = [
  {
    id: 213,
    dataplan_id: '213',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 275,
    dataplan_id: '275',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 7,
    name: '7.0GB',
  },
  {
    id: 395,
    dataplan_id: '395',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 2,
    name: '2.0GB',
  },
  {
    id: 414,
    dataplan_id: '414',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 3,
    name: '1.0GB',
  },
  {
    id: 443,
    dataplan_id: '443',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 30,
    name: '13.0GB',
  },
  {
    id: 445,
    dataplan_id: '445',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.5GB',
  },
  {
    id: 446,
    dataplan_id: '446',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 2,
    name: '4.0GB',
  },
  {
    id: 447,
    dataplan_id: '447',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 7,
    name: '3.0GB',
  },
  {
    id: 448,
    dataplan_id: '448',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 1,
    name: '1.0GB',
  },
  {
    id: 449,
    dataplan_id: '449',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 1,
    name: '1.5GB',
  },
  {
    id: 450,
    dataplan_id: '450',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 1,
    name: '1.0GB',
  },
  {
    id: 451,
    dataplan_id: '451',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 1,
    name: '150.0MB',
  },
  {
    id: 452,
    dataplan_id: '452',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 2,
    name: '300.0MB',
  },
  {
    id: 453,
    dataplan_id: '453',
    network_id: 4,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 2,
    name: '600.0MB',
  },
];

export const airtelPlans: Array<DataPlan> = [
  ...airtelSmePlans,
  ...airtelGiftingPlans,
  ...airtelCorporatePlans,
  ...airtelAwoofPlans,
];
