import { DataPlan } from './plans.dto';

const etisalatCorporatePlans: Array<DataPlan> = [
  {
    id: 355,
    dataplan_id: '355',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 356,
    dataplan_id: '356',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 357,
    dataplan_id: '357',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 358,
    dataplan_id: '358',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 359,
    dataplan_id: '359',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 361,
    dataplan_id: '361',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '20.0GB',
  },
  {
    id: 362,
    dataplan_id: '362',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '500.0MB',
  },
  {
    id: 374,
    dataplan_id: '374',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '15.0GB',
  },
  {
    id: 459,
    dataplan_id: '459',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '4.0GB',
  },
  {
    id: 460,
    dataplan_id: '460',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '11.0GB',
  },
  {
    id: 461,
    dataplan_id: '461',
    network_id: 3,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '7.5GB',
  },
];

const etisalatGiftingPlans: Array<DataPlan> = [
  {
    id: 182,
    dataplan_id: '182',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '500.0MB',
  },
  {
    id: 183,
    dataplan_id: '183',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.5GB',
  },
  {
    id: 184,
    dataplan_id: '184',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 185,
    dataplan_id: '185',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 186,
    dataplan_id: '186',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '4.5GB',
  },
  {
    id: 187,
    dataplan_id: '187',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '11.0GB',
  },
  {
    id: 188,
    dataplan_id: '188',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '7.0GB',
  },
  {
    id: 189,
    dataplan_id: '189',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '40.0GB',
  },
  {
    id: 190,
    dataplan_id: '190',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '75.0GB',
  },
  {
    id: 310,
    dataplan_id: '310',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '250.0MB',
  },
  {
    id: 312,
    dataplan_id: '312',
    network_id: 3,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.0GB',
  },
];

export const etisalatPlans: Array<DataPlan> = [
  ...etisalatGiftingPlans,
  ...etisalatCorporatePlans,
];
