import { DataPlan } from './plans.dto';

const gloGiftingPlans: Array<DataPlan> = [
  {
    id: 246,
    dataplan_id: '246',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 14,
    name: '1.35GB',
  },
  {
    id: 247,
    dataplan_id: '247',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.9GB',
  },
  {
    id: 248,
    dataplan_id: '248',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.8GB',
  },
  {
    id: 250,
    dataplan_id: '250',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '7.7GB',
  },
  {
    id: 251,
    dataplan_id: '251',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 252,
    dataplan_id: '252',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '13.25GB',
  },
  {
    id: 255,
    dataplan_id: '255',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '50.0GB',
  },
  {
    id: 256,
    dataplan_id: '256',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '93.0GB',
  },
  {
    id: 257,
    dataplan_id: '257',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '29.5GB',
  },
  {
    id: 269,
    dataplan_id: '269',
    network_id: 2,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '4.1GB',
  },
];

const gloCorporatePlans: Array<DataPlan> = [
  {
    id: 319,
    dataplan_id: '319',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 320,
    dataplan_id: '320',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 321,
    dataplan_id: '321',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 322,
    dataplan_id: '322',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 323,
    dataplan_id: '323',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 324,
    dataplan_id: '324',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '500.0MB',
  },
  {
    id: 325,
    dataplan_id: '325',
    network_id: 2,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '200.0MB',
  },
];

const gloAwoofPlans: Array<DataPlan> = [
  {
    id: 442,
    dataplan_id: '442',
    network_id: 2,
    plan_type: 'DATA AWOOF',
    validity_unit: 'day',
    validity_value: 1,
    name: '750.0MB',
  },
];

export const gloPlans = [
  ...gloGiftingPlans,
  ...gloCorporatePlans,
  ...gloAwoofPlans,
];
