import { DataPlan } from './plans.dto';

const mtnSmePlans: Array<DataPlan> = [
  {
    id: 235,
    dataplan_id: '235',
    network_id: 1,
    plan_type: 'SME',
    validity_value: 7,
    validity_unit: 'day',
    name: '1.0GB',
  },
  {
    id: 237,
    dataplan_id: '237',
    network_id: 1,
    plan_type: 'SME',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 239,
    dataplan_id: '239',
    network_id: 1,
    plan_type: 'SME',
    validity_value: 30,
    validity_unit: 'day',
    name: '7.0GB',
  },
  {
    id: 240,
    dataplan_id: '240',
    network_id: 1,
    plan_type: 'SME',
    validity_value: 7,
    validity_unit: 'day',
    name: '500MB',
  },
  {
    id: 266,
    dataplan_id: '266',
    network_id: 1,
    plan_type: 'SME',
    validity_value: 30,
    validity_unit: 'day',
    name: '10.0GB',
  },
  {
    id: 309,
    dataplan_id: '309',
    network_id: 1,
    plan_type: 'SME',
    validity_value: 30,
    validity_unit: 'day',
    name: '3.5GB',
  },
];

const mtnSme2Plans: Array<DataPlan> = [
  {
    id: 332,
    dataplan_id: '332',
    network_id: 1,
    plan_type: 'SME2',
    validity_unit: 'day',
    validity_value: 30,
    name: '500.0MB',
  },
  {
    id: 333,
    dataplan_id: '333',
    network_id: 1,
    plan_type: 'SME2',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 334,
    dataplan_id: '334',
    network_id: 1,
    plan_type: 'SME2',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 335,
    dataplan_id: '335',
    network_id: 1,
    plan_type: 'SME2',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 336,
    dataplan_id: '336',
    network_id: 1,
    plan_type: 'SME2',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 337,
    dataplan_id: '337',
    network_id: 1,
    plan_type: 'SME2',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
];
const mtnCorporatePlans: Array<DataPlan> = [
  {
    id: 285,
    dataplan_id: '285',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 286,
    dataplan_id: '286',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 287,
    dataplan_id: '287',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 288,
    dataplan_id: '288',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 289,
    dataplan_id: '289',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_value: 30,
    validity_unit: 'day',
    name: '10.0GB',
  },
  {
    id: 290,
    dataplan_id: '290',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '15.0GB',
  },
  {
    id: 291,
    dataplan_id: '291',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '20.0GB',
  },
  {
    id: 292,
    dataplan_id: '292',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '40.0GB',
  },
  {
    id: 293,
    dataplan_id: '293',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '500.0MB',
  },
  {
    id: 311,
    dataplan_id: '311',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '250.0MB',
  },
  {
    id: 360,
    dataplan_id: '360',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '15.0GB',
  },
];

const mtnCorporate2Plans: Array<DataPlan> = [
  {
    id: 338,
    dataplan_id: '338',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 339,
    dataplan_id: '339',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 340,
    dataplan_id: '340',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
  {
    id: 341,
    dataplan_id: '341',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '4.0GB',
  },
  {
    id: 342,
    dataplan_id: '342',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 343,
    dataplan_id: '343',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '6.0GB',
  },
  {
    id: 344,
    dataplan_id: '344',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '7.0GB',
  },
  {
    id: 345,
    dataplan_id: '345',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '8.0GB',
  },
  {
    id: 346,
    dataplan_id: '346',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '9.0GB',
  },
  {
    id: 347,
    dataplan_id: '347',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0MB',
  },
  {
    id: 348,
    dataplan_id: '348',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '15.0GB',
  },
  {
    id: 349,
    dataplan_id: '349',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '20.0GB',
  },
  {
    id: 350,
    dataplan_id: '350',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '25.0GB',
  },
  {
    id: 351,
    dataplan_id: '351',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '300.0MB',
  },
  {
    id: 352,
    dataplan_id: '352',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '100.0MB',
  },
  {
    id: 353,
    dataplan_id: '353',
    network_id: 1,
    plan_type: 'CORPORATE GIFTING 2',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.5GB',
  },
];

const mtnGiftingPlans: Array<DataPlan> = [
  {
    id: 241,
    dataplan_id: '241',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 242,
    dataplan_id: '242',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 1,
    name: '1.0GB',
  },
  {
    id: 244,
    dataplan_id: '244',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '6.0GB',
  },
  {
    id: 260,
    dataplan_id: '260',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '3.2GB',
  },
  {
    id: 261,
    dataplan_id: '261',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '2.0GB',
  },
  {
    id: 376,
    dataplan_id: '376',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '10.0GB',
  },
  {
    id: 377,
    dataplan_id: '377',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '16.5GB',
  },
  {
    id: 378,
    dataplan_id: '378',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '12.5GB',
  },
  {
    id: 379,
    dataplan_id: '379',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '32.0GB',
  },
  {
    id: 380,
    dataplan_id: '380',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '150.0GB',
  },
  {
    id: 383,
    dataplan_id: '383',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.5GB',
  },
  {
    id: 384,
    dataplan_id: '384',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.0GB',
  },
  {
    id: 386,
    dataplan_id: '386',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '25.0GB',
  },
  {
    id: 387,
    dataplan_id: '387',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '20.0GB',
  },
  {
    id: 388,
    dataplan_id: '388',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '75.0GB',
  },
  {
    id: 389,
    dataplan_id: '389',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.2GB',
  },
  {
    id: 390,
    dataplan_id: '390',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '6.75GB',
  },
  {
    id: 391,
    dataplan_id: '391',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '14.5GB',
  },
  {
    id: 392,
    dataplan_id: '392',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.7GB',
  },
  {
    id: 397,
    dataplan_id: '397',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '1.5GB',
  },
  {
    id: 426,
    dataplan_id: '426',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '200.0GB',
  },
  {
    id: 430,
    dataplan_id: '430',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 3,
    name: '750.0MB',
  },
  {
    id: 431,
    dataplan_id: '431',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 1,
    name: '500.0MB',
  },
  {
    id: 432,
    dataplan_id: '432',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 2,
    name: '2.5GB',
  },
  {
    id: 433,
    dataplan_id: '433',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '1.8GB',
  },
  {
    id: 434,
    dataplan_id: '434',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '3.5GB',
  },
  {
    id: 435,
    dataplan_id: '435',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.5GB',
  },
  {
    id: 436,
    dataplan_id: '436',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '7.0GB',
  },
  {
    id: 437,
    dataplan_id: '437',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '20.0GB',
  },
  {
    id: 438,
    dataplan_id: '438',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '35.0GB',
  },
  {
    id: 439,
    dataplan_id: '439',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '36.0GB',
  },
  {
    id: 454,
    dataplan_id: '454',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 7,
    name: '470.0MB',
  },
  {
    id: 455,
    dataplan_id: '455',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.2GB',
  },
  {
    id: 456,
    dataplan_id: '456',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 1,
    name: '110.0MB',
  },
  {
    id: 458,
    dataplan_id: '458',
    network_id: 1,
    plan_type: 'GIFTING',
    validity_unit: 'day',
    validity_value: 1,
    name: '2.5GB',
  },
];

const mtnDataShare: Array<DataPlan> = [
  {
    id: 370,
    dataplan_id: '370',
    network_id: 1,
    plan_type: 'DATA SHARE',
    validity_unit: 'day',
    validity_value: 30,
    name: '1.0GB',
  },
  {
    id: 371,
    dataplan_id: '371',
    network_id: 1,
    plan_type: 'DATA SHARE',
    validity_unit: 'day',
    validity_value: 30,
    name: '2.0GB',
  },
  {
    id: 372,
    dataplan_id: '372',
    network_id: 1,
    plan_type: 'DATA SHARE',
    validity_unit: 'day',
    validity_value: 30,
    name: '5.0GB',
  },
  {
    id: 373,
    dataplan_id: '373',
    network_id: 1,
    plan_type: 'DATA SHARE',
    validity_unit: 'day',
    validity_value: 30,
    name: '3.0GB',
  },
];

const mtnDataCoupons: Array<DataPlan> = [
  {
    id: 365,
    dataplan_id: '365',
    network_id: 1,
    plan_type: 'DATA COUPONS',
    validity_unit: 'day',
    validity_value: 1,
    name: '1.0GB',
  },
  {
    id: 367,
    dataplan_id: '367',
    network_id: 1,
    plan_type: 'DATA COUPONS',
    validity_unit: 'day',
    validity_value: 7,
    name: '7.0GB',
  },
  {
    id: 368,
    dataplan_id: '368',
    network_id: 1,
    plan_type: 'DATA COUPONS',
    validity_unit: 'day',
    validity_value: 2,
    name: '3.2GB',
  },
];

export const mtnPlans: Array<DataPlan> = [
  ...mtnSmePlans,
  ...mtnSme2Plans,
  ...mtnGiftingPlans,
  ...mtnCorporatePlans,
  ...mtnCorporate2Plans,
  ...mtnDataShare,
  ...mtnDataCoupons,
];
